### ISSUE TITLE
Values under 40 and over 160 in the meal form.

### ISSUE THREAD

**Issue by rober-web** [nasinghw/Project-1#57]
When we set values under 40 and over 160 in the meal input weight, the API lauches error:

GET https://fitness-calculator.p.rapidapi.com/macrocalculator?age=30&gender=female&height=161&weight=161&activitylevel=4&goal=maintain 422 (Unprocessable Content)

The solution should be limiting the values to stay between the accepted by the API.

**Comment by rober-web** [comment]
Also, the height input only allows people above 130cm and below 230 cm.

It seems the API has some limitations. Will have to check the documentation.

**Comment by Pazoraf** [comment]
I'll get to work on this!

**Comment by Pazoraf** [comment]
If checks added to prevent this error from occuring
