### ISSUE TITLE
On the submit for the about yourself form, prevent the modal from launching if some of the fields are missing/not valid

### ISSUE THREAD

**Issue by Pazoraf** [nasinghw/Project-1#64]

**Comment by rober-web** [comment]
Resolved:

Removed data-bs-toggle="modal" and data-bs-target="#modal-calories from "#about-submit" button.
Added such data attributes dynamically through "#about-form" on submit event.

  $("#about-submit").attr({ "data-bs-toggle": "modal", "data-bs-target": "#modal-calories" });
  $('#modal-calories').modal('show'); 
  
  Also added   document.location.reload() to the reset button to prevent the data cleared from local storage staying in memory cache.
